### PR TITLE
add if for run-ext.txt

### PR DESCRIPTION
**Pull request by Tieqiong**
closes #55

### CODE REVIEW

**Comment by bobleesj** [comment]
> closes #55 

I thought of this, but don't you also have to apply if then for pip.txt?

**Comment by bobleesj** [comment]
Also 2 other yml files also need "if then" if we decide to implement this

**Comment by bobleesj** [comment]
@Tieqiong @sbillinge 

What if we use a single command to install all conda packages at once so that the dependency sorting can be handled at once?

```
conda install \                          
    --file requirements/run.txt \                  
    --file requirements/run-ext.txt \                  
    --file requirements/test.txt \
    --file requirements/pip.txt \
    --file requirements/build.txt
```

**Comment by sbillinge** [comment]
Can you say some more words about what problem this solves? I am not sure what you mean by "dependency solving"?

**Comment by bobleesj** [comment]
@sbillinge 

> Can you say some more words about what problem this solves? I am not sure what you mean by "dependency solving"?

When multiple packages listed in files like text.txt, build.txt, and run.txt are installed together in a single command, Conda can more effectively analyze and resolve the dependencies of all packages in one unified process. 

This means there won't be instances where downgrades or upgrades are needed between separate Conda install commands.

**Comment by sbillinge** [comment]
I see, that makes sense then.  However it presumably makes more difficult, though not impossible, conditional installs?

**Comment by sbillinge** [comment]
I wonder if it is better to not have the `run-ext.txt` in the cookiecutter

**Comment by sbillinge** [comment]
sorry, clicked the wrong thing there by mistake.

**Comment by sbillinge** [comment]
> what if we include `run-ext.txt` dependencies under `run.txt`? This was a special case for `diffpy.srfit`

sorry, not sure what you mean here.  Normally I would say that edge cases can deviate from the cookie-cutter if they are rare.  We like to keep such cases to a minimum.  But because we have the release scripts centralized, we would have to have a separate yaml presumably for each edge case, either residing in the local directory of the edge case, or here centrally, but the local yml updated to call a differently named yaml from here?   Or we can find a way to catch all the edge cases with conditionals (which also adds unwanted complexity).

**Comment by sbillinge** [comment]
Closing on basis that we have change this to conda/pip

**Pull request closed without merging**
